export const FOOD_DATABASE = {
  "minecraft:apple": { nutrition: 4, saturationModifier: 0.3 },
  "minecraft:appleEnchanted": {
    nutrition: 4,
    saturationModifier: 2.4,
    can_always_eat: true,
    effects: [
      { name: "regeneration", chance: 1, duration: 30, amplifier: 1 },
      { name: "absorption", chance: 1, duration: 120, amplifier: 3 },
      { name: "resistance", chance: 1, duration: 300, amplifier: 0 },
      { name: "fire_resistance", chance: 1, duration: 300, amplifier: 0 },
    ],
  },
  "minecraft:baked_potato": { nutrition: 5, saturationModifier: 1.2 },
  "minecraft:beef": { nutrition: 3, saturationModifier: 0.6 },
  "minecraft:beetroot": { nutrition: 1, saturationModifier: 1.2 },
  "minecraft:beetroot_soup": {
    nutrition: 6,
    saturationModifier: 1.2,
    using_converts_to: "bowl",
  },
  "minecraft:bread": { nutrition: 5, saturationModifier: 1.2 },
  "minecraft:carrot": { nutrition: 3, saturationModifier: 1.2 },
  "minecraft:chicken": {
    nutrition: 2,
    saturationModifier: 0.6,
    effects: [{ name: "hunger", chance: 0.3, duration: 30, amplifier: 0 }],
  },
  "minecraft:chorus_fruit": {
    nutrition: 4,
    saturationModifier: 0.6,
    on_use_action: "chorus_teleport",
    on_use_range: [8, 8, 8],
    cooldown_type: "chorusfruit",
    cooldown_time: 20,
    can_always_eat: true,
  },
  "minecraft:clownfish": { nutrition: 1, saturationModifier: 0.2 },
  "minecraft:cooked_beef": { nutrition: 8, saturationModifier: 1.6 },
  "minecraft:cooked_chicken": { nutrition: 6, saturationModifier: 1.2 },
  "minecraft:cooked_cod": { nutrition: 5, saturationModifier: 1.2 },
  "minecraft:cooked_porkchop": { nutrition: 8, saturationModifier: 1.6 },
  "minecraft:cooked_rabbit": { nutrition: 5, saturationModifier: 1.2 },
  "minecraft:cooked_salmon": { nutrition: 6, saturationModifier: 1.6 },
  "minecraft:cookie": { nutrition: 2, saturationModifier: 0.2 },
  "minecraft:dried_kelp": { nutrition: 1, saturationModifier: 0.2 },
  "minecraft:cod": { nutrition: 2, saturationModifier: 0.2 },
  "minecraft:glow_berries": {
    nutrition: 2,
    saturationModifier: 0.6,
    is_meat: false,
  },
  "minecraft:golden_apple": {
    nutrition: 4,
    saturationModifier: 2.4,
    can_always_eat: true,
    effects: [
      { name: "regeneration", chance: 1, duration: 5, amplifier: 1 },
      { name: "absorption", chance: 1, duration: 120, amplifier: 0 },
    ],
  },
  "minecraft:golden_carrot": {
    nutrition: 6,
    saturationModifier: 2.4,
  },
  "minecraft:honey_bottle": {
    nutrition: 6,
    saturationModifier: 0.2,
    can_always_eat: true,
    using_converts_to: "glass_bottle",
    remove_effects: ["poison"],
  },
  "minecraft:melon_slice": { nutrition: 2, saturationModifier: 0.6 },
  "minecraft:mushroom_stew": {
    nutrition: 6,
    saturationModifier: 1.2,
    using_converts_to: "bowl",
  },
  "minecraft:muttonCooked": { nutrition: 6, saturationModifier: 1.6 },
  "minecraft:muttonRaw": { nutrition: 2, saturationModifier: 0.6 },
  "minecraft:poisonous_potato": {
    nutrition: 2,
    saturationModifier: 0.6,
    effects: [{ name: "poison", chance: 0.6, duration: 5, amplifier: 0 }],
  },
  "minecraft:porkchop": { nutrition: 3, saturationModifier: 0.6 },
  "minecraft:potato": { nutrition: 1, saturationModifier: 0.6 },
  "minecraft:pufferfish": {
    nutrition: 1,
    saturationModifier: 0.2,
    effects: [
      { name: "poison", duration: 60, amplifier: 1 },
      { name: "nausea", duration: 15, amplifier: 0 },
      { name: "hunger", duration: 15, amplifier: 2 },
    ],
  },
  "minecraft:pumpkin_pie": { nutrition: 8, saturationModifier: 0.6 },
  "minecraft:rabbit": { nutrition: 3, saturationModifier: 0.6 },
  "minecraft:rabbit_stew": {
    nutrition: 10,
    saturationModifier: 1.2,
    using_converts_to: "bowl",
  },
  "minecraft:rotten_flesh": {
    nutrition: 4,
    saturationModifier: 0.2,
    effects: [{ name: "hunger", chance: 0.8, duration: 30, amplifier: 0 }],
  },
  "minecraft:salmon": { nutrition: 2, saturationModifier: 0.2 },
  "minecraft:spider_eye": {
    nutrition: 2,
    saturationModifier: 1.6,
    effects: [{ name: "poison", chance: 1, duration: 5, amplifier: 0 }],
  },
  "minecraft:suspicious_stew": {
    nutrition: 6,
    saturationModifier: 1.2,
    using_converts_to: "bowl",
    on_use_action: "suspicious_stew_effect",
    can_always_eat: true,
  },
  "minecraft:sweet_berries": {
    nutrition: 2,
    saturationModifier: 0.6,
    is_meat: false,
  },
};
